workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 30

    environment:
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"

    triggering:
      events:
        - push

    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build Release APK
        script: ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "chaudharyamit46533@gmail.com"
