workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 60

    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build Release APK
        script: ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
